version: '3'
services:
  dockerapp:
    image: zinovyev/dockerapp-rb
    ports:
      - '4000:4567'
    depends_on:
      - redis
    deploy:
      replicas: 2
  redis:
    image: 'redis:3.2'
    deploy:
      replicas: 2
